List<Map<String, dynamic>> currency_List = [
  {
    "coinType": "ETH",
    "chainType": 0,
    "token": "ETH",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 0,
    "tokenType": 0,
  },
  {
    "coinType": "ETH",
    "chainType": 0,
    "token": "ETH",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 1,
    "tokenType": 0,
  },
  {
    "coinType": "BSC",
    "chainType": 1,
    "token": "BNB",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 0,
    "tokenType": 0,
  },
  {
    "coinType": "BSC",
    "chainType": 1,
    "token": "BNB",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 1,
    "tokenType": 0,
  },
  {
    "coinType": "HECO",
    "chainType": 2,
    "token": "HT",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 0,
    "tokenType": 0,
  },
  {
    "coinType": "HECO",
    "chainType": 2,
    "token": "HT",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 1,
    "tokenType": 0,
  },
  {
    "coinType": "OKChain",
    "chainType": 3,
    "token": "OKT",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 0,
    "tokenType": 0,
  },
  {
    "coinType": "OKChain",
    "chainType": 3,
    "token": "OKT",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 1,
    "tokenType": 0,
  },
  {
    "coinType": "Matic",
    "chainType": 4,
    "token": "MATIC",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 0,
    "tokenType": 0,
  },
  {
    "coinType": "Matic",
    "chainType": 4,
    "token": "MATIC",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 1,
    "tokenType": 0,
  },
  {
    "coinType": "AVAX",
    "chainType": 5,
    "token": "AVAX",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 0,
    "tokenType": 0,
  },
  {
    "coinType": "AVAX",
    "chainType": 5,
    "token": "AVAX",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 1,
    "tokenType": 0,
  },
  {
    "coinType": "Arbitrum",
    "chainType": 6,
    "token": "Arbitrum",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 0,
    "tokenType": 0,
  },
  {
    "coinType": "Arbitrum",
    "chainType": 6,
    "token": "Arbitrum",
    "decimals": 18,
    "contract": "",
    "digits": 6,
    "kNetType": 1,
    "tokenType": 0,
  },
  {
    "coinType": "ETH",
    "chainType": 0,
    "token": "USDT",
    "decimals": 6,
    "contract": "0xdac17f958d2ee523a2206206994597c13d831ec7",
    "digits": 4,
    "kNetType": 0,
    "tokenType": 1,
  },
  {
    "coinType": "ETH",
    "chainType": 0,
    "token": "TUSD",
    "decimals": 18,
    "contract": "0x0000000000085d4780B73119b644AE5ecd22b376",
    "digits": 4,
    "kNetType": 0,
    "tokenType": 1,
  },
  {
    "coinType": "ETH",
    "chainType": 0,
    "token": "GUSD",
    "decimals": 2,
    "contract": "0x056fd409e1d7a124bd7017459dfea2f387b6d5cd",
    "digits": 4,
    "kNetType": 0,
    "tokenType": 1,
  }
];
